export const SECONDS_IN_MINUTE = 60;
export const MINUTES_IN_HOUR = 60;
export const HOURS_IN_DAY = 24;
export const DAYS_IN_WEEK = 7;
export const DAYS_IN_MONTH = 30;
export const DAYS_IN_YEAR = 365;

export const SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE;
export const SECONDS_IN_DAY = HOURS_IN_DAY * SECONDS_IN_HOUR;

export const MILLIS_IN_SECOND = 1000;
export const MILLIS_IN_MINUTE = MILLIS_IN_SECOND * SECONDS_IN_MINUTE;
export const MILLIS_IN_HOUR = MILLIS_IN_SECOND * SECONDS_IN_HOUR;
export const MILLIS_IN_DAY = MILLIS_IN_SECOND * SECONDS_IN_DAY;

export const MONTHS_IN_A_YEAR = 12;
